http://localhost:8080/exam/java/add?question=QuestionText&answer=QuestionAnswer
###
http://localhost:8080/exam/java/remove?question=QuestionText&answer=QuestionAnswer
###
http://localhost:8080/exam/java
###






